=== kharkov-ant/MyPractice/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nure.ua/kharkov/SummaryTask3/entity"
	xmlns:tns="http://nure.ua/kharkov/SummaryTask3/entity">

	<xsd:element name="OldCards">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="OldCard" type="tns:OldCard"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="OldCard">
		<xsd:sequence>
			<xsd:element name="Thema" type="xsd:string" />
			<xsd:sequence>
				<xsd:element name="Type" type="tns:Type" />
			</xsd:sequence>
			<xsd:element name="Country" type="xsd:string" />
			<xsd:element name="Year" type="xsd:gYear" />
			<xsd:element name="Author" type="xsd:string"
				minOccurs="0" maxOccurs="4" />
			<xsd:element name="Valuable" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Type" mixed="true">
		<xsd:attribute name="send" type="xsd:boolean"
			default="false" />
	</xsd:complexType>
</xsd:schema>

=== kharkov-ant/MyPractice/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<myxml:OldCards
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:myxml="http://nure.ua/kharkov/SummaryTask3/entity"
	xsi:schemaLocation="http://nure.ua/kharkov/SummaryTask3/entity input.xsd">
	<OldCard>
		<Thema>Nature</Thema>
		<Type send="true">Normal</Type>
		<Country>Ukraine</Country>
		<Year>2001</Year>
		<Author>Ivan Beda</Author>
		<Author>Anton Bobov</Author>
		<Valuable>Thematic</Valuable>
	</OldCard>

	<OldCard>
		<Thema>People</Thema>
		<Type>Normal</Type>
		<Country>USA</Country>
		<Year>1968</Year>
		<Valuable>Historical</Valuable>
	</OldCard>

	<OldCard>
		<Thema>Sport</Thema>
		<Type>Advertising</Type>
		<Country>USA</Country>
		<Year>2010</Year>
		<Author>James Onil</Author>
		<Valuable>Thematic</Valuable>
	</OldCard>

</myxml:OldCards>
